CREATE TABLE IF NOT EXISTS ratings (
                                       id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS categories (
                                          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS movies (
                                      id INTEGER PRIMARY KEY,
                                      name VARCHAR(255) NOT NULL,
                                      description VARCHAR(200) NOT NULL,
                                      release_date DATE NOT NULL,
                                      duration INTEGER CHECK (duration > 0),
                                      rating_id INTEGER REFERENCES ratings(id)
);

CREATE TABLE IF NOT EXISTS movie_categories (
                                                movie_id INTEGER REFERENCES movies(id),
                                                category_id INTEGER REFERENCES categories(id)
);

CREATE TABLE IF NOT EXISTS members (
                                       id INTEGER PRIMARY KEY,
                                       email VARCHAR(255) NOT NULL,
                                       login VARCHAR(255) NOT NULL,
                                       name VARCHAR(255),
                                       birthday DATE
);

CREATE TABLE IF NOT EXISTS buddies (
                                       member_id INTEGER REFERENCES members(id),
                                       buddy_id INTEGER REFERENCES members(id)
);

CREATE TABLE IF NOT EXISTS hearts (
                                      movie_id INTEGER REFERENCES movies(id),
                                      member_id INTEGER REFERENCES members(id)
);